services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "server"
      FLASK_ENV: "development"
      PYTHONPATH: "/app"
    volumes:
      - ${BACKEND_VOLUME_PATH}:/app  # Mount the absolute path on your local machine
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

