services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "server"
      FLASK_ENV: "development"
      PYTHONPATH: "/app"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: ${RUNTIME:-runc}  # Fallback to CPU if RUNTIME is not set
