[project]
name = "backend"
version = "1.1.0"
dependencies = [
    "Flask>3.0.0",
    "joblib~=1.4.2",
    "protobuf~=5.28.0",
    "google~=3.0.0",
    "numpy~=1.24.2",
    "scipy==1.14.1",
    "orjson~=3.10.15"
]
requires-python = ">=3.10"
authors = [
    { name = "Doron Firman", email = "doronfi3@gmail.com" },
]
maintainers = [
    { name = "Doron Firman", email = "doronfi3@gmail.com" },
]
description = "Basic flask server for ECG data"
#readme = "README.rst"
#license = {file = "LICENSE.txt"}
keywords = ["AI", "ML", "ECG"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.10"
]

[tool.setuptools]
packages = ["server", "instance"]